# .github/workflows/ci.yml
name: CI Pipeline

# 👇 This section defines when the workflow should run.
on:
  push:
    branches:
      - main             # Run CI on push to main branch
  pull_request:
    branches:
      - main             # Also run CI when PR is made to main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  build-docs:
      needs: build-project
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install MkDocs
          run: |
            pip install mkdocs

        - name: Build MkDocs site
          run: |
            mkdocs build

        - name: Upload site as artifact
          uses: actions/upload-artifact@v4
          with:
            name: mkdocs-site
            path: site/
            
  docker-build-and-push:
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-project:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-project:latest